In [3]:
import numpy as np

In [5]:
l=[1,2,3,4,5]
np.array(l)

array([1, 2, 3, 4, 5])

In [7]:
l1=[4,5,6,7,"aimnxt",34.565,True]

In [9]:
a1=np.array(l1)
a1

array(['4', '5', '6', '7', 'aimnxt', '34.565', 'True'], dtype='<U32')

In [11]:
a2=np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [15]:
a1.ndim

1

In [17]:
a2.ndim

2

In [19]:
a3.ndim

3

In [21]:
a1.size

7

In [23]:
a2.size

6

In [25]:
a3.size

9

In [27]:
a1.shape

(7,)

In [29]:
a2.shape

(2, 3)

In [31]:
a3.shape

(1, 3, 3)

In [33]:
a=np.random.randint(2,50,(2,3,4))
a.ndim

3

In [35]:
np.random.randint(1,10,(1,4,3))

array([[[2, 9, 3],
        [2, 7, 8],
        [8, 2, 5],
        [8, 6, 9]]])

In [37]:
np.random.randint(2,100,(3,5,6))

array([[[45, 41, 80, 32, 60, 31],
        [74, 62, 68, 15, 44, 81],
        [57, 71, 15, 67, 21,  6],
        [59, 95,  3, 89, 77, 61],
        [78, 16, 79, 70, 94, 88]],

       [[ 2, 64, 59, 99, 63, 53],
        [75, 33, 62, 32, 18, 36],
        [58,  4, 57, 12, 12, 17],
        [55, 87, 82, 49, 53, 61],
        [59, 50, 81,  2, 59,  6]],

       [[47, 15, 98, 65, 31, 46],
        [78,  7, 84, 98, 93, 24],
        [62, 42, 47, 60, 50, 67],
        [23, 95, 58, 76, 21, 56],
        [60, 66, 87, 36, 24,  6]]])

In [39]:
np.random.rand(3,3)

array([[0.55969845, 0.22584226, 0.26442633],
       [0.817135  , 0.11012234, 0.7017427 ],
       [0.93973326, 0.63103425, 0.14379699]])

In [41]:
a4=np.random.randn(4,3)
a4

array([[ 1.18365802,  0.57407244,  2.40434495],
       [ 0.39534982, -0.43102556,  0.45193565],
       [ 0.02516711, -1.15447794,  1.12735697],
       [ 0.71847432,  0.46274937,  1.84586112]])

In [43]:
a4.reshape(3,4)

array([[ 1.18365802,  0.57407244,  2.40434495,  0.39534982],
       [-0.43102556,  0.45193565,  0.02516711, -1.15447794],
       [ 1.12735697,  0.71847432,  0.46274937,  1.84586112]])

In [45]:
a4[0]

array([1.18365802, 0.57407244, 2.40434495])

In [47]:
a1[4]

'aimnxt'

In [49]:
a1[6]

'True'

In [51]:
a1[2:6]

array(['6', '7', 'aimnxt', '34.565'], dtype='<U32')

In [53]:
a1[2:6:2]

array(['6', 'aimnxt'], dtype='<U32')

In [55]:
a1[::-1]

array(['True', '34.565', 'aimnxt', '7', '6', '5', '4'], dtype='<U32')

In [57]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
a2[:,1:]

array([[2, 3],
       [5, 6]])

In [61]:
a2[[0,1],1:]

array([[2, 3],
       [5, 6]])

In [104]:
a5=np.random.randint(2,90,(6,5))
a5

array([[55, 35, 39, 34, 52],
       [27, 35, 85, 63, 66],
       [10, 38, 26, 51, 57],
       [45, 55, 10, 16, 36],
       [64, 47, 69, 40, 43],
       [84, 22, 68, 79,  6]])

In [65]:
a5[a5>40]

array([69, 73, 44, 62, 43, 80, 50, 68, 45, 79, 59, 76, 68, 67, 51, 87, 80,
       86])

In [67]:
a5[a5>60]

array([69, 73, 62, 80, 68, 79, 76, 68, 67, 87, 80, 86])

In [69]:
a5[0,1]=100

In [71]:
a5

array([[ 69, 100,  44,   6,  24],
       [ 62,   4,  43,  33,  27],
       [ 18,  23,  80,  16,  50],
       [ 68,  19,  45,  79,  59],
       [ 13,  76,  68,  17,  67],
       [ 51,  87,  80,  86,   8]])

In [73]:
a5[2,3]=100

In [75]:
a5

array([[ 69, 100,  44,   6,  24],
       [ 62,   4,  43,  33,  27],
       [ 18,  23,  80, 100,  50],
       [ 68,  19,  45,  79,  59],
       [ 13,  76,  68,  17,  67],
       [ 51,  87,  80,  86,   8]])

In [112]:
a6=np.random.randint(0,3,(3,3))

In [114]:
a6

array([[2, 0, 1],
       [0, 1, 0],
       [0, 2, 0]])

In [120]:
a7=np.random.randint(0,3,(3,3))
a7

array([[0, 2, 2],
       [1, 0, 2],
       [0, 2, 1]])

In [124]:
a6*a7

array([[0, 0, 2],
       [0, 0, 0],
       [0, 4, 0]])

In [126]:
a6@a7

array([[0, 6, 5],
       [1, 0, 2],
       [2, 0, 4]])

In [87]:
a6/0

C:\Users\lenovo\AppData\Local\Temp\ipykernel_4012\1058679823.py:1: RuntimeWarning: divide by zero encountered in divide
  a6/0
C:\Users\lenovo\AppData\Local\Temp\ipykernel_4012\1058679823.py:1: RuntimeWarning: invalid value encountered in divide
  a6/0


array([[inf, nan, inf],
       [inf, inf, inf],
       [nan, inf, nan]])

In [118]:
a6*2

array([[4, 0, 2],
       [0, 2, 0],
       [0, 4, 0]])

In [116]:
a6**3

array([[8, 0, 1],
       [0, 1, 0],
       [0, 8, 0]], dtype=int32)

In [93]:
a6**100

array([[0, 0, 1],
       [0, 1, 1],
       [0, 1, 0]], dtype=int32)

In [95]:
a8=np.zeros((4,4))

In [97]:
a8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [106]:
a5[2,2]=1000

In [108]:
a5

array([[  55,   35,   39,   34,   52],
       [  27,   35,   85,   63,   66],
       [  10,   38, 1000,   51,   57],
       [  45,   55,   10,   16,   36],
       [  64,   47,   69,   40,   43],
       [  84,   22,   68,   79,    6]])

In [110]:
a5[3,1]=1000
a5

array([[  55,   35,   39,   34,   52],
       [  27,   35,   85,   63,   66],
       [  10,   38, 1000,   51,   57],
       [  45, 1000,   10,   16,   36],
       [  64,   47,   69,   40,   43],
       [  84,   22,   68,   79,    6]])

In [134]:
a9=np.ones((4,5))

In [136]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [138]:
a9+10

array([[11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.]])

In [140]:
a9+np.array([1,2,3,4,5])

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [142]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [146]:
np.array([[1,2,3,4,5]]).T

array([[1],
       [2],
       [3],
       [4],
       [5]])

### column wise broadcasting


In [149]:
np.array([[1,2,3,4]]).T+a9

array([[2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [151]:
a5

array([[  55,   35,   39,   34,   52],
       [  27,   35,   85,   63,   66],
       [  10,   38, 1000,   51,   57],
       [  45, 1000,   10,   16,   36],
       [  64,   47,   69,   40,   43],
       [  84,   22,   68,   79,    6]])

In [153]:
np.sqrt(a5)

array([[ 7.41619849,  5.91607978,  6.244998  ,  5.83095189,  7.21110255],
       [ 5.19615242,  5.91607978,  9.21954446,  7.93725393,  8.1240384 ],
       [ 3.16227766,  6.164414  , 31.6227766 ,  7.14142843,  7.54983444],
       [ 6.70820393, 31.6227766 ,  3.16227766,  4.        ,  6.        ],
       [ 8.        ,  6.8556546 ,  8.30662386,  6.32455532,  6.55743852],
       [ 9.16515139,  4.69041576,  8.24621125,  8.88819442,  2.44948974]])

In [155]:
np.exp(a5)

C:\Users\lenovo\AppData\Local\Temp\ipykernel_4012\252965343.py:1: RuntimeWarning: overflow encountered in exp
  np.exp(a5)


array([[7.69478527e+23, 1.58601345e+15, 8.65934004e+16, 5.83461743e+14,
        3.83100800e+22],
       [5.32048241e+11, 1.58601345e+15, 8.22301271e+36, 2.29378316e+27,
        4.60718663e+28],
       [2.20264658e+04, 3.18559318e+16,            inf, 1.40934908e+22,
        5.68572000e+24],
       [3.49342711e+19,            inf, 2.20264658e+04, 8.88611052e+06,
        4.31123155e+15],
       [6.23514908e+27, 2.58131289e+20, 9.25378173e+29, 2.35385267e+17,
        4.72783947e+18],
       [3.02507732e+36, 3.58491285e+09, 3.40427605e+29, 2.03828107e+34,
        4.03428793e+02]])

In [157]:
np.log10(a5)

array([[1.74036269, 1.54406804, 1.59106461, 1.53147892, 1.71600334],
       [1.43136376, 1.54406804, 1.92941893, 1.79934055, 1.81954394],
       [1.        , 1.5797836 , 3.        , 1.70757018, 1.75587486],
       [1.65321251, 3.        , 1.        , 1.20411998, 1.5563025 ],
       [1.80617997, 1.67209786, 1.83884909, 1.60205999, 1.63346846],
       [1.92427929, 1.34242268, 1.83250891, 1.89762709, 0.77815125]])

In [159]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [161]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [165]:
range(1,10,0.5)

TypeError: 'float' object cannot be interpreted as an integer

In [169]:
np.linspace(2,3,num=50,retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [171]:
np.logspace(2,4,num=4)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [173]:
np.logspace(2,4,num=4,base=10)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [175]:
np.logspace(2,4,num=4,base=2)

array([ 4.        ,  6.34960421, 10.0793684 , 16.        ])

In [177]:
#identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [179]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])