In [8]:
import pandas as pd
import numpy as np
data=pd.read_csv('spam.csv', encoding='ISO-8859-1')
data

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [10]:
df=data[['v1','v2']]
df

v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [12]:
df.shape

(5572, 2)

In [14]:
df.isnull().sum()

v1    0
v2    0
dtype: int64

In [16]:
df['v1'].unique()

array(['ham', 'spam'], dtype=object)

In [18]:
df['v1'].value_counts()

v1
ham     4825
spam     747
Name: count, dtype: int64

In [22]:
df['v1']=df['v1'].apply(lambda x:0 if x=='ham' else 1)

C:\Users\lenovo\AppData\Local\Temp\ipykernel_9584\2819141581.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['v1']=df['v1'].apply(lambda x:0 if x=='ham' else 1)


In [24]:
df['v1'].value_counts()

v1
0    4825
1     747
Name: count, dtype: int64

In [28]:
df['v2']=df['v2'].str.lower()

C:\Users\lenovo\AppData\Local\Temp\ipykernel_9584\653301761.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['v2']=df['v2'].str.lower()


In [30]:
df.head()

v1                                                 v2
0   0  go until jurong point, crazy.. available only ...
1   0                      ok lar... joking wif u oni...
2   1  free entry in 2 a wkly comp to win fa cup fina...
3   0  u dun say so early hor... u c already then say...
4   0  nah i don't think he goes to usf, he lives aro...

In [32]:
import re
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [34]:
from bs4 import BeautifulSoup

In [36]:
## Removing special characters
df['v2']=df['v2'].apply(lambda x:re.sub('[^a-z A-z 0-9-]+', '',x))
## Remove the stopswords
df['v2']=df['v2'].apply(lambda x:" ".join([y for y in x.split() if y not in stopwords.words('english')]))
## Remove url
df['v2']=df['v2'].apply(lambda x: re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/+#-]*[\w@?^=%&/+#-])?', '' , str(x)))
## Remove html tags
df['v2']=df['v2'].apply(lambda x: BeautifulSoup(x, 'lxml').get_text())
## Remove any additional spaces
df['v2']=df['v2'].apply(lambda x: " ".join(x.split()))

C:\Users\lenovo\AppData\Local\Temp\ipykernel_9584\3319845505.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['v2']=df['v2'].apply(lambda x:re.sub('[^a-z A-z 0-9-]+', '',x))
C:\Users\lenovo\AppData\Local\Temp\ipykernel_9584\3319845505.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['v2']=df['v2'].apply(lambda x:" ".join([y for y in x.split() if y not in stopwords.words('english')]))
C:\Users\lenovo\AppData\Local\Temp\ipykernel_9584\3319845505.py:6: SettingWithCopyWarning: 
A value is trying to 

In [37]:
df.head()

v1                                                 v2
0   0  go jurong point crazy available bugis n great ...
1   0                            ok lar joking wif u oni
2   1  free entry 2 wkly comp win fa cup final tkts 2...
3   0                u dun say early hor u c already say
4   0        nah dont think goes usf lives around though

In [40]:
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [42]:
lemmatizer=WordNetLemmatizer()

In [44]:
def lemmatize_words(text):
  return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

In [46]:
df['v2']=df['v2'].apply(lambda x:lemmatize_words(x))

C:\Users\lenovo\AppData\Local\Temp\ipykernel_9584\3227305118.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['v2']=df['v2'].apply(lambda x:lemmatize_words(x))


In [48]:
df.head()

v1                                                 v2
0   0  go jurong point crazy available bugis n great ...
1   0                            ok lar joking wif u oni
2   1  free entry 2 wkly comp win fa cup final tkts 2...
3   0                u dun say early hor u c already say
4   0           nah dont think go usf life around though

In [50]:
df['v2'][0]

'go jurong point crazy available bugis n great world la e buffet cine got amore wat'

In [52]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df['v2'],df['v1'],test_size=0.2)

In [54]:
from sklearn.feature_extraction.text import CountVectorizer

bow=CountVectorizer()

X_train_bow=bow.fit_transform(X_train).toarray()

X_test_bow=bow.transform(X_test).toarray()

In [56]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
X_train_tfidf=tfidf.fit_transform(X_train).toarray()
X_test_tfidf=tfidf.transform(X_test).toarray()

In [58]:
X_train_bow

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [60]:
from sklearn.naive_bayes import GaussianNB
nb_model_bow=GaussianNB().fit(X_train_bow,y_train)
nb_model_tfidf=GaussianNB().fit(X_train_tfidf,y_train)

In [62]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [64]:
y_pred_bow=nb_model_bow.predict(X_test_bow)
y_pred_tfidf=nb_model_tfidf.predict(X_test_tfidf)

In [66]:
confusion_matrix(y_test,y_pred_bow)

array([[866, 108],
       [ 11, 130]], dtype=int64)

In [68]:
print("BOW accuracy: ",accuracy_score(y_test,y_pred_bow))

BOW accuracy:  0.8932735426008969


In [70]:
confusion_matrix(y_test,y_pred_tfidf)

array([[866, 108],
       [ 14, 127]], dtype=int64)

In [72]:
print("TFIDF accuracy: ",accuracy_score(y_test,y_pred_tfidf))

TFIDF accuracy:  0.8905829596412556


In [74]:
print(classification_report(y_test,y_pred_bow))

              precision    recall  f1-score   support

           0       0.99      0.89      0.94       974
           1       0.55      0.92      0.69       141

    accuracy                           0.89      1115
   macro avg       0.77      0.91      0.81      1115
weighted avg       0.93      0.89      0.90      1115



In [76]:
print(classification_report(y_test,y_pred_tfidf))

              precision    recall  f1-score   support

           0       0.98      0.89      0.93       974
           1       0.54      0.90      0.68       141

    accuracy                           0.89      1115
   macro avg       0.76      0.89      0.80      1115
weighted avg       0.93      0.89      0.90      1115

